import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export default function TermsOfService() {
  return (
    <div className="flex min-h-screen w-full flex-col items-center bg-transparent text-foreground">
      <div className="w-full max-w-7xl px-4 sm:px-6 lg:px-8">
        <header className="flex w-full items-center justify-between py-4 md:py-6 border-b border-border/50">
          <Link href="/" className="flex items-center gap-3">
            <Image src="/assets/logo-main.png" alt="Humanize AI Logo" width={160} height={40} priority style={{ objectFit: 'contain', aspectRatio: '160 / 40' }} />
          </Link>
          <Button asChild>
            <Link href="/">Back to Home</Link>
          </Button>
        </header>

        <main className="flex w-full flex-grow flex-col items-center py-8 md:py-12">
            <div className="w-full max-w-3xl space-y-8">
                <div className="text-center">
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
                        Terms of Service
                    </h2>
                     <p className="mx-auto mt-4 max-w-[700px] text-lg text-muted-foreground md:text-xl">
                        Last updated: {new Date().toLocaleDateString()}
                    </p>
                </div>
                <div className="prose prose-lg dark:prose-invert max-w-none">
                    <h3>1. Acceptance of Terms</h3>
                    <p>
                        By accessing and using HumanizeAI Pro, you accept and agree to be bound by the terms and provision of this agreement.
                    </p>
                    <h3>2. Service Description</h3>
                    <p>
                        HumanizeAI Pro provides text humanization and SEO optimization services. The services are provided "as is" and we make no warranty of any kind regarding the accuracy, reliability, or completeness of the AI-generated content.
                    </p>
                    <h3>3. User Conduct</h3>
                    <p>
                        You agree not to use the service for any illegal or unauthorized purpose. You are responsible for all your activity in connection with the services and for the content you generate.
                    </p>
                    <h3>4. Intellectual Property</h3>
                    <p>
                        The service and its original content (excluding content generated by users), features, and functionality are and will remain the exclusive property of HumanizeAI Pro and its licensors. You retain ownership of the content you generate, but you grant us a license to use, store, and process it to provide and improve our services.
                    </p>
                    <h3>5. Disclaimer of Liability</h3>
                     <p>
                        The content generated by our AI is for informational purposes only and should be reviewed for accuracy and appropriateness by a human. We are not liable for any errors, omissions, or any consequences arising from the use of the generated content.
                    </p>
                    <h3>6. Termination</h3>
                    <p>
                        We may terminate or suspend access to our service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                    </p>
                </div>
            </div>
        </main>
      </div>
    </div>
  );
}
