
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export default function TermsOfService() {
  return (
    <div className="flex min-h-screen w-full flex-col items-center bg-transparent text-foreground">
      <div className="w-full max-w-7xl px-4 sm:px-6 lg:px-8">
        <header className="flex w-full items-center justify-between py-4 md:py-6 border-b border-border/50">
          <Link href="/" className="flex items-center gap-3">
            <Image src="/assets/logo-main.png" alt="Humanize AI Logo" width={160} height={40} priority style={{ objectFit: 'contain', aspectRatio: '160 / 40' }} />
          </Link>
          <Button asChild>
            <Link href="/">Back to Home</Link>
          </Button>
        </header>

        <main className="flex w-full flex-grow flex-col items-center py-8 md:py-12">
            <div className="w-full max-w-3xl space-y-8">
                <div className="text-center">
                    <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
                        Terms of Service
                    </h1>
                     <p className="mx-auto mt-4 max-w-[700px] text-lg text-muted-foreground md:text-xl">
                        Last updated: {new Date().toLocaleDateString()}
                    </p>
                </div>
                <div className="prose prose-lg dark:prose-invert max-w-none">
                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By using HumanizeAI Pro, you agree to these terms. Our service provides a powerful <strong>AI to human converter</strong> designed to help you <strong>humanize AI text</strong>. These terms govern your use of our tools to <strong>bypass AI detectors</strong>.
                    </p>
                    <h2>2. Use of Service</h2>
                    <p>
                        You agree to use our service responsibly. The output generated by our tool is intended to assist you, but you are ultimately responsible for the final content. Our tool is designed to <strong>bypass AI detection</strong>, but we do not guarantee that all content will be 100% undetectable in all scenarios.
                    </p>
                    <h2>3. Intellectual Property</h2>
                    <p>
                        You retain full ownership of the text you submit and the humanized content you receive. We claim no rights over your work. Our goal is simply to provide the best <strong>AI to human converter</strong> on the market.
                    </p>

                    <hr className="my-8" />
                    
                    <div dir="rtl" className="text-right">
                        <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
                            شروط الخدمة
                        </h1>
                        <h2>1. قبول الشروط</h2>
                        <p>
                            باستخدامك لـ HumanizeAI Pro، فإنك توافق على هذه الشروط. توفر خدمتنا <strong>محول AI إلى نص بشري</strong> قوي مصمم لمساعدتك على <strong>أنسنة نص الذكاء الاصطناعي</strong>. تحكم هذه الشروط استخدامك لأدواتنا <strong>لتجاوز كواشف الذكاء الاصطناعي</strong>.
                        </p>
                        <h2>2. استخدام الخدمة</h2>
                        <p>
                            أنت توافق على استخدام خدمتنا بمسؤولية. المحتوى الذي تم إنشاؤه بواسطة أداتنا يهدف إلى مساعدتك، لكنك المسؤول النهائي عن المحتوى النهائي. تم تصميم أداتنا <strong>لتجاوز كشف الذكاء الاصطناعي</strong>، لكننا لا نضمن أن كل المحتوى سيكون غير قابل للكشف بنسبة 100% في جميع السيناريوهات.
                        </p>
                        <h2>3. الملكية الفكرية</h2>
                        <p>
                            أنت تحتفظ بالملكية الكاملة للنص الذي تقدمه والمحتوى المؤنسن الذي تتلقاه. نحن لا ندعي أي حقوق على عملك. هدفنا هو ببساطة توفير أفضل <strong>محول AI إلى نص بشري</strong> في السوق.
                        </p>
                    </div>
                </div>
            </div>
        </main>
      </div>
    </div>
  );
}
